### ISSUE TITLE
Add job for deployment with ember-cli-deploy

### ISSUE THREAD

**Issue by GreatWizard** [GreatWizard/ember-circleci#4]
- Detect ember-cli-deploy plugin
- Add deploy job (filter to activate only on branch master by default)

**Comment by adambedford** [comment]
This would be great! We're looking now for the best way to move the build & deploy process from a local machine to a CI environment.

**Comment by GreatWizard** [comment]
If you already setup ember-cli-deploy, the job in CircleCI config can be defined like:

```yaml
jobs:
  ## Add this Job
  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Run Deploy
          command: yarn ember deploy production

workflows:
  version: 2
  test_and_deploy:
    jobs:
      ## Add this to the workflow
      - deploy:
          requires:
            - test
            - test_lts_3_12
            - test_lts_3_16
            - test_lts_3_20
            - test_release
            - test_beta
            - test_canary
            - test_default_with_jquery
            - test_classic
          filters:
            branches:
              only:
                - master
```

I guess if I'm adding a deploy option it will generate theses line for you.
And then you have to adapt to which environement you are going to deploy and if you need more ember-cli-deploy options (coming from addons)
